# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweeper', '0002_auto_20170426_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='adjacent_mines',
            field=models.PositiveSmallIntegerField(default='0'),
        ),
    ]
